run_args:
  experiment_name: linear_projection
  description:

modalities:
  posts:
    ocr:
      modality: ocr_combined

model:
  _target_: models.Retrieval_Project
  emb_dim: ${args.emb_dim}
  tied: false
  tied_init: true
  linear_init: ${method:torch.nn.init.orthogonal_}
