run_args:
  experiment_name: opti_free_concat[unnormalized]
  description:

args:
  normalize_features: false

modalities:
  posts:
    ocr:
      modality: ocr_combined
      
model:
  _target_: models.Retrieval_Concat

~optimizer:

trainer:
  _target_: routines.DummyTrainer
