run_args:
  experiment_name: opti_free_concat[ocr]
  description:
  
args:
  normalize_features: true

modalities:
  posts:
    ~image:
    ~text:
    ocr:
      modality: ocr_combined
      
model:
  _target_: models.Retrieval_Concat

~optimizer:

trainer:
  _target_: routines.DummyTrainer
